import { useState, useCallback } from 'react';
import { loadFromUrl } from './lib/loader';
import type { OnboardingPackage } from './lib/loader';
import { PRESET_REPOS } from './lib/repos';
import type { PresetRepo } from './lib/repos';
import RepoSelector from './components/RepoSelector';
import OverviewSection from './components/OverviewSection';
import LayoutSection from './components/LayoutSection';
import FlowsSection from './components/FlowsSection';
import ApiSection from './components/ApiSection';
import DatabaseSection from './components/DatabaseSection';
import SetupSection from './components/SetupSection';
import GapsSection from './components/GapsSection';
import './index.css';

const NAV_ITEMS = [
  { id: 'overview',  label: 'Overview & Tech Stack', icon: '📋' },
  { id: 'layout',    label: 'Layout & Modules',       icon: '📁' },
  { id: 'flows',     label: 'Data Flows & Deps',      icon: '🔄' },
  { id: 'api',       label: 'API Endpoints',          icon: '🌐' },
  { id: 'database',  label: 'Database Model',         icon: '🗄️' },
  { id: 'setup',     label: 'Setup & New Module',     icon: '✅' },
  { id: 'gaps',      label: 'Gaps & Notes',           icon: '⚠️' },
] as const;

type SectionId = (typeof NAV_ITEMS)[number]['id'];

export default function App() {
  // Which repo is currently selected (null = landing selector)
  const [selectedRepo, setSelectedRepo] = useState<PresetRepo | null>(null);
  const [pkg, setPkg] = useState<OnboardingPackage | null>(null);
  const [errors, setErrors] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState<SectionId>('overview');
  const [search, setSearch] = useState('');

  const handleSelectRepo = useCallback(async (repo: PresetRepo) => {
    setLoading(true);
    setLoadError(null);
    setPkg(null);
    setErrors([]);
    setActiveSection('overview');
    setSearch('');

    try {
      const { data, errors: errs } = await loadFromUrl(repo.jsonPath);
      setPkg(data);
      setErrors(errs);
      setSelectedRepo(repo);
    } catch (err) {
      setLoadError(`Failed to load onboarding guide: ${String(err)}`);
      setSelectedRepo(repo); // still show the repo context with the error
    } finally {
      setLoading(false);
    }
  }, []);

  const handleBack = useCallback(() => {
    setSelectedRepo(null);
    setPkg(null);
    setErrors([]);
    setLoadError(null);
    setSearch('');
    setActiveSection('overview');
  }, []);

  // ── Landing / selector screen ──────────────────────────────────────────────
  if (!selectedRepo && !loading) {
    return <RepoSelector repos={PRESET_REPOS} onSelect={handleSelectRepo} />;
  }

  // ── Loading state (between selection and data ready) ───────────────────────
  if (loading) {
    return (
      <div className="loading-screen">
        <div className="loading-spinner" />
        <p>Loading onboarding guide…</p>
      </div>
    );
  }

  // ── Dashboard ──────────────────────────────────────────────────────────────
  return (
    <div className="app-shell">
      {/* Sidebar */}
      <aside className="sidebar">
        <div className="sidebar-header">
          <div className="sidebar-logo">Repo<span>Guide</span></div>
          <div className="sidebar-subtitle">Onboarding Dashboard</div>
        </div>

        {/* Repo switcher */}
        <div className="sidebar-repo-info">
          <div className="sidebar-repo-icon">{selectedRepo?.icon}</div>
          <div className="sidebar-repo-name">{selectedRepo?.name ?? ''}</div>
          <a
            href={selectedRepo?.githubUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="sidebar-repo-link"
            title="Open on GitHub"
          >
            ↗ GitHub
          </a>
          <button className="sidebar-back-btn" onClick={handleBack}>
            ← All repos
          </button>
        </div>

        <nav className="sidebar-nav">
          {NAV_ITEMS.map(item => (
            <button
              key={item.id}
              className={`nav-item${activeSection === item.id ? ' active' : ''}`}
              onClick={() => setActiveSection(item.id)}
            >
              <span className="nav-icon">{item.icon}</span>
              {item.label}
            </button>
          ))}
        </nav>

        <div className="sidebar-footer">
          Guide generated by IBM Bob<br />
          <span style={{ fontSize: 10 }}>No live analysis</span>
        </div>
      </aside>

      {/* Main */}
      <main className="main-content">
        {/* Topbar */}
        <header className="topbar">
          <div className="topbar-title">
            {selectedRepo?.name ?? ''}{' '}
            <span>— Bob onboarding guide (demo)</span>
          </div>

          {/* Search */}
          <div className="search-bar">
            <span className="search-icon">🔍</span>
            <input
              type="text"
              placeholder="Search all sections…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              aria-label="Search"
            />
            {search && (
              <button
                onClick={() => setSearch('')}
                style={{
                  background: 'none', border: 'none', cursor: 'pointer',
                  color: 'var(--muted)', fontSize: 14, lineHeight: 1, padding: 0,
                }}
                aria-label="Clear search"
              >✕</button>
            )}
          </div>

          {/* Repo switcher dropdown (topbar) */}
          <select
            className="topbar-repo-switcher"
            value={selectedRepo?.id ?? ''}
            onChange={e => {
              const repo = PRESET_REPOS.find(r => r.id === e.target.value);
              if (repo && repo.status === 'ready') handleSelectRepo(repo);
            }}
            aria-label="Switch repository"
          >
            {PRESET_REPOS.map(r => (
              <option key={r.id} value={r.id} disabled={r.status === 'pending'}>
                {r.icon} {r.name}{r.status === 'pending' ? ' (guide pending)' : ''}
              </option>
            ))}
          </select>
        </header>

        {/* Content */}
        <div className="content-area">
          {/* Demo notice */}
          <div className="demo-notice-banner">
            🎯 <strong>Demo</strong> — This guide was prepared in advance by IBM Bob.
            Selecting a repository does not trigger live analysis.{' '}
            <a href={selectedRepo?.githubUrl} target="_blank" rel="noopener noreferrer">
              View <strong>{selectedRepo?.githubPath}</strong> on GitHub ↗
            </a>
          </div>

          {/* Load error */}
          {loadError && (
            <div className="error-banner">
              <h3>Failed to load onboarding guide</h3>
              <p style={{ fontSize: 12 }}>{loadError}</p>
            </div>
          )}

          {/* Validation warnings */}
          {errors.length > 0 && (
            <div className="error-banner">
              <h3>
                Schema validation issues ({errors.length})
                <span style={{ fontWeight: 400 }}> — some sections may be incomplete</span>
              </h3>
              <ul>
                {errors.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            </div>
          )}

          {/* Dashboard sections */}
          {pkg && (
            <>
              {activeSection === 'overview'  && <OverviewSection  pkg={pkg} search={search} />}
              {activeSection === 'layout'    && <LayoutSection    pkg={pkg} search={search} />}
              {activeSection === 'flows'     && <FlowsSection     pkg={pkg} search={search} />}
              {activeSection === 'api'       && <ApiSection       pkg={pkg} search={search} />}
              {activeSection === 'database'  && <DatabaseSection  pkg={pkg} search={search} />}
              {activeSection === 'setup'     && <SetupSection     pkg={pkg} search={search} />}
              {activeSection === 'gaps'      && <GapsSection      pkg={pkg} search={search} />}
            </>
          )}
        </div>
      </main>
    </div>
  );
}
